services:
  db:
    image: postgres:16
    container_name: movielib_db
    environment:
      POSTGRES_DB: movielib
      POSTGRES_USER: movielib_user
      POSTGRES_PASSWORD: movielib_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U movielib_user -d movielib"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
