server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/movielib}
    username: ${SPRING_DATASOURCE_USERNAME:movielib_user}
    password: ${SPRING_DATASOURCE_PASSWORD:movielib_pass}
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

tmdb:
  api-key: ${TMDB_API_KEY}
  image-url: ${TMDB_IMAGE_URL:https://image.tmdb.org/t/p/w500}
