server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movielib
    username: movielib_user
    password: movielib_pass
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

tmdb:
  api-key: 9594807b52677b8ac0d880e4783484aa
  image-url: https://image.tmdb.org/t/p/w500